# Generated by Django 5.2 on 2025-10-09 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_regtd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=50, unique=True)),
                ('lab_name', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='lab_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='1234', max_length=20)),
                ('lab_name', models.CharField(max_length=20)),
                ('lab_id', models.CharField(max_length=15)),
                ('lab_location', models.CharField(max_length=100)),
                ('lab_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('lab_open', models.TimeField()),
                ('lab_close', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
