# Generated by Django 5.2 on 2025-10-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('lab_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee_rgtd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=50)),
                ('lab_name', models.CharField(max_length=50)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
