# Generated by Django 5.2 on 2025-10-09 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('p_name', models.CharField(max_length=20)),
                ('p_age', models.CharField(max_length=2)),
                ('p_add', models.CharField(max_length=50)),
                ('p_pincode', models.CharField(max_length=6)),
                ('p_gender', models.CharField(max_length=10)),
                ('p_date', models.DateField(auto_now=True)),
                ('p_contact', models.CharField(max_length=10)),
                ('test_type', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='labs.lab_user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
